services:
  laravel:
    container_name: laravel-php82
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - laravel_vendor:/var/www/html/vendor
    depends_on:
      - mysql

volumes:
  laravel_vendor:
